# Generated by Django 3.0.7 on 2020-07-09 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watching',
            field=models.ManyToManyField(related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
