# Generated by Django 3.0.7 on 2020-07-09 16:50

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200709_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[auctions.models.valid_bid]),
        ),
    ]
